WORDS = {
    'ru': {
        'start_keyboard': {'cats': '\U0001F4C2 Категории',
                           'news': '\U0001F4E2 Последние новости',
                           'info': '\U00002139 Информация для покупателя',
                           'cart': '\U0001F6D2 Корзина',
                           'hist': '\U0001F4DC История заказов'
                           },
        'cats': '*Категории*',
        'text_cart': '\U0001F6D2 Корзина',
        'text_detals': 'Подробно',
        'kg': 'кг',
        'g': 'г',
        'weight': 'вес:',
        'quantity': 'доступно:',
        'empty': 'Корзина пуста',
        'remove': 'Удалить продукт из корзины',
        'checkout': 'Оформить заказ',
        'confirm': 'Подтвердите Ваш заказ',
        'thanks': 'Спасибо за заказ!',
        'history_empty': 'История пуста',
        'order_sum': 'Сумма заказа:'
    },
    'en': {
        'start_keyboard': {'cats': '\U0001F4C2 Category',
                           'news': '\U0001F4E2 Last news',
                           'info': '\U00002139 Information',
                           'cart': '\U0001F6D2 Cart',
                           'hist': '\U0001F4DC Order history'},
        'cats': '*Categories*',
        'text_cart': '\U0001F6D2 Cart',
        'text_detals': 'Detals',
        'kg': 'kg',
        'g': 'g',
        'weight': 'weight:',
        'quantity': 'available:',
        'empty': 'cart empty',
        'remove': 'remove',
        'checkout': 'Checkout',
        'confirm': 'Confirm your order',
        'thanks': 'Thank you for the order!',
        'history_empty': 'The history is empty',
        'order_sum': 'Order price:'
    }
}
